# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: chipsncode
google_analytics: dbyll

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Chips'nCode Blog

description: Stylish Jekyll Theme
author:
  name: Marzogh
  email: marzogh@icloud.com
  github: marzogh
  twitter: PrajwalBM
  pinterest: asd123
  linkedin: asd123
  bio: Jack of many trades, master of some
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: http://marzogh.github.io/blog
