# visit http://jekyllrb.com/docs/frontmatter/ for more settings

gems: [jekyll-paginate]
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
timezone: Australia/Brisbane
highlighter: rouge
markdown: kramdown
disqus: chipsncode
google_analytics:

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Chips'nCode Blog
      keywords: electronics, code, arduino, raspberry pi, SPIFlash, flash, memory, winbond, open source, DIY, maker, hacker
### content configuration ###

description: Pushing the boundaries of what I can do, one line of code & one wire at a time
source_link:
favicon:
touch_icon:

author:
  name: Marzogh
  email: marzogh@icloud.com
  github: marzogh
  twitter: Marzogh_
  #pinterest: asd123
  #linkedin: asd123
  bio: Jack of many trades, master of some
  email_md5: 18f94b6a6b0a37ee759005c81e838e4a

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: http://marzogh.github.io/blog
